// Proposal/invoice HTML renderer with workspace branding. Pure.
// All dynamic strings are HTML-escaped at render time.

export interface PricingLine {
  description: string;
  amountCents: number;
}

export interface ProposalData {
  summary: string;
  scopeItems: string[];
  pricingLines: PricingLine[];
  terms: string[];
  totalCents: number;
}

export interface BrandInfo {
  name: string;
  color: string;
  logoUrl?: string | null;
}

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function totalCents(lines: PricingLine[]): number {
  return lines.reduce((sum, l) => sum + (Number.isFinite(l.amountCents) ? l.amountCents : 0), 0);
}

export function fmtMoney(cents: number, currency = "USD"): string {
  const symbols: Record<string, string> = { USD: "$", EUR: "€", GBP: "£" };
  const sym = symbols[currency] ?? "$";
  return `${sym}${(cents / 100).toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
}

export function proposalHtml(brand: BrandInfo, data: ProposalData, clientName: string, currency = "USD"): string {
  const color = /^#[0-9a-fA-F]{3,8}$/.test(brand.color) ? brand.color : "#10b981";
  const esc = escapeHtml;
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Proposal — ${esc(clientName)}</title></head>
<body style="margin:0;background:#f4f4f5;font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;color:#18181b">
  <div style="max-width:720px;margin:0 auto;background:#ffffff;padding:48px;min-height:100vh">
    <div style="display:flex;justify-content:space-between;align-items:center;border-bottom:3px solid ${esc(color)};padding-bottom:20px">
      <div>
        ${brand.logoUrl ? `<img src="${esc(brand.logoUrl)}" alt="logo" style="height:36px;margin-bottom:8px" />` : ""}
        <div style="font-size:22px;font-weight:800;letter-spacing:-0.02em">${esc(brand.name || "CrewOS")}</div>
        <div style="font-size:12px;color:#71717a;margin-top:2px">Prepared for <strong>${esc(clientName)}</strong> · ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</div>
      </div>
      <div style="background:${esc(color)};color:#022c22;font-weight:800;padding:8px 14px;border-radius:8px;font-size:13px">PROPOSAL</div>
    </div>

    <h2 style="font-size:16px;margin:32px 0 8px;letter-spacing:.05em;color:#71717a">SUMMARY</h2>
    <p style="font-size:14px;line-height:1.7;color:#3f3f46">${esc(data.summary)}</p>

    <h2 style="font-size:16px;margin:32px 0 8px;letter-spacing:.05em;color:#71717a">SCOPE</h2>
    <ul style="font-size:14px;line-height:1.9;color:#3f3f46;padding-left:20px;margin:0">
      ${data.scopeItems.map((s) => `<li>${esc(s)}</li>`).join("\n      ")}
    </ul>

    <h2 style="font-size:16px;margin:32px 0 8px;letter-spacing:.05em;color:#71717a">INVESTMENT</h2>
    <table style="width:100%;border-collapse:collapse;font-size:14px">
      ${data.pricingLines
        .map(
          (l) => `<tr>
        <td style="padding:10px 0;border-bottom:1px solid #e4e4e7">${esc(l.description)}</td>
        <td style="padding:10px 0;border-bottom:1px solid #e4e4e7;text-align:right;font-variant-numeric:tabular-nums">${fmtMoney(l.amountCents, currency)}</td>
      </tr>`,
        )
        .join("\n      ")}
      <tr>
        <td style="padding:14px 0;font-weight:800">Total</td>
        <td style="padding:14px 0;font-weight:800;text-align:right;font-variant-numeric:tabular-nums;font-size:16px">${fmtMoney(data.totalCents, currency)}</td>
      </tr>
    </table>

    <h2 style="font-size:16px;margin:32px 0 8px;letter-spacing:.05em;color:#71717a">TERMS</h2>
    <ul style="font-size:13px;line-height:1.8;color:#52525b;padding-left:20px;margin:0">
      ${data.terms.map((t) => `<li>${esc(t)}</li>`).join("\n      ")}
    </ul>

    <div style="margin-top:48px;padding-top:16px;border-top:1px solid #e4e4e7;font-size:12px;color:#a1a1aa;display:flex;justify-content:space-between">
      <span>${esc(brand.name || "CrewOS")} · Generated by CrewOS</span>
      <span>Signature: ______________________</span>
    </div>
  </div>
</body></html>`;
}
