import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { getSession } from "@/lib/auth/session";
import { redirect } from "next/navigation";
import { PrintButton } from "@/components/print-button";

export const dynamic = "force-dynamic";

export default async function DocumentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const session = await getSession();
  if (!session) redirect("/login");

  const doc = await prisma.document.findFirst({ where: { id, workspaceId: session.wsId } });
  if (!doc) notFound();

  return (
    <div className="space-y-4">
      <div className="no-print flex items-center justify-between">
        <Link href="/app/documents" className="text-sm font-semibold text-zinc-500 hover:text-emerald-500">
          ← All documents
        </Link>
        <PrintButton />
      </div>
      {/* Generated by our own template with HTML-escaped content at creation time. */}
      <div
        className="overflow-hidden rounded-xl border border-zinc-200 dark:border-zinc-800 [&_body]:!bg-white"
        dangerouslySetInnerHTML={{ __html: doc.html }}
      />
    </div>
  );
}
